### ISSUE TITLE
Configurable Parameters for JRTC

### ISSUE THREAD

**Issue by doctorlai-msrc** [microsoft/jrt-controller#24]
We need to provide a configurable system e.g. yaml file that allows uers to configure the namespace, run_path etc.

As a user, I would like to pass configurations in a yaml file like this:

```bash
${JRTC_OUT_DIR}/bin/jrtc --config=config.yaml
```

A `config.yaml` looks like this:

```yaml
jrtc_router_config:
    thread_config:
        affinity_mask: 2
        hash_sched_config: false
        ### ...

jbpf_io_config:
    jbpf_namespace: "jrtc"
    jbpf_path: "/var/run/jbpf"
    ### ...

some_other_sessions_if_needed:
   ### ...
```

To avoid hard-coded parameters such as [here](https://github.com/microsoft/jrt-controller/blob/main/src/router/jrtc_router.c#L317C1-L323C61) when jrtc starts, it will read from a `default.yaml` and users can supply a custom yaml as shown above to override the parameters.

When `default.yaml` is not present - we can print a warning message but continue with hard-coded values. At least, the hard-coded parameters need to be defined in a separate header.h file.

The yaml file should also support ENV expansion. e.g. `${ENV}`
